export const restaurants = [
  {
    id: 'amina',
    name: 'Chez Amina',
    shortName: 'Amina',
    cuisine: 'Cuisine marocaine',
    district: 'Paris 11e',
    distance: '800 m',
    rating: '4,9',
    image: '/images/table.webp',
    address: '18 rue des Trois-Bornes, Paris 11e',
    description: 'Une table de quartier chaleureuse pour les tajines, couscous et légumes aux épices douces.',
    hours: ['Vendredi · 11:30–23:00', 'Samedi · 12:00–23:30'],
    diets: ['Halal', 'Végétarien'],
    loyalty: {
      type: 'stamps',
      title: 'Les saveurs d’Amina',
      current: 9,
      target: 10,
      reward: 'Un plat signature offert',
      rule: 'Une coche par visite, hors boissons.',
      style: 'braise',
    },
    menu: [
      { name: 'Couscous du vendredi', description: 'Semoule fine, légumes confits et poulet aux épices douces.', price: '18,50 €' },
      { name: 'Tajine citron', description: 'Poulet fermier, citron confit et olives violettes.', price: '19,50 €' },
      { name: 'Carottes à la chermoula', description: 'Entrée fraîche aux herbes, cumin et agrumes.', price: '7,50 €' },
    ],
  },
  {
    id: 'casa',
    name: 'Casa Verde',
    shortName: 'Casa Verde',
    cuisine: 'Cuisine mexicaine',
    district: 'Paris 11e',
    distance: '1,1 km',
    rating: '4,6',
    image: '/images/tacos.webp',
    address: '22 rue Oberkampf, Paris 11e',
    description: 'Tortillas pressées chaque matin, légumes rôtis, salsa verde et citron frais.',
    hours: ['Vendredi · 12:00–23:00', 'Samedi · 12:00–00:00'],
    diets: ['Végétarien', 'Végan'],
    loyalty: {
      type: 'stamps',
      title: 'La mesa verde',
      current: 6,
      target: 8,
      reward: 'Un dessert maison offert',
      rule: 'Une coche par passage.',
      style: 'braise',
    },
    menu: [
      { name: 'Tacos de légumes rôtis', description: 'Salsa verde, avocat et citron vert.', price: '14,00 €' },
      { name: 'Quesadilla maison', description: 'Fromage fumé, haricots noirs et coriandre.', price: '13,50 €' },
    ],
  },
  {
    id: 'miso',
    name: 'Atelier Miso',
    shortName: 'Atelier Miso',
    cuisine: 'Cuisine japonaise',
    district: 'Paris 10e',
    distance: '1,4 km',
    rating: '4,8',
    image: '/images/ramen.webp',
    address: '7 passage du Marché, Paris 10e',
    description: 'Ramen, bols et petites assiettes japonaises cuisinés dans un atelier calme et végétal.',
    hours: ['Vendredi · 18:00–23:00', 'Samedi · 12:00–23:00'],
    diets: ['Végétarien', 'Végan', 'Sans gluten'],
    loyalty: {
      type: 'points',
      title: 'Le cercle Miso',
      current: 740,
      target: 800,
      reward: 'Un menu midi offert',
      rule: 'Dix points par euro dépensé.',
      style: 'braise',
    },
    menu: [
      { name: 'Ramen miso blanc', description: 'Bouillon végétal, nouilles, shiitakés et œuf mariné.', price: '17,90 €' },
      { name: 'Donburi aubergine', description: 'Riz vinaigré, aubergine laquée et pickles maison.', price: '16,50 €' },
      { name: 'Gyozas de saison', description: 'Légumes, ponzu et huile de sésame.', price: '8,50 €' },
    ],
  },
  {
    id: 'comptoir',
    name: 'Le Comptoir Solaire',
    shortName: 'Comptoir Solaire',
    cuisine: 'Brunch méditerranéen',
    district: 'Paris 2e',
    distance: '2 km',
    rating: '4,7',
    image: '/images/table.webp',
    address: '8 rue du Nil, Paris 2e',
    description: 'Assiettes de saison, café de spécialité et grandes tablées.',
    hours: ['Tous les jours · 09:00–18:00'],
    diets: ['Végétarien'],
    loyalty: {
      type: 'points',
      title: 'Les matins solaires',
      current: 320,
      target: 500,
      reward: 'Un brunch offert',
      rule: 'Cinq points par euro dépensé.',
      style: 'creme',
    },
    menu: [
      { name: 'Assiette solaire', description: 'Œufs, légumes rôtis et labneh.', price: '17,00 €' },
      { name: 'Granola maison', description: 'Yaourt, fruits de saison et miel.', price: '9,50 €' },
    ],
  },
  {
    id: 'rizrouge',
    name: 'Riz Rouge',
    shortName: 'Riz Rouge',
    cuisine: 'Cuisine thaïlandaise',
    district: 'Paris 10e',
    distance: '1,7 km',
    rating: '4,7',
    image: '/images/ramen.webp',
    address: '14 rue du Faubourg, Paris 10e',
    description: 'Bols parfumés, herbes fraîches et assiettes à partager dans une salle lumineuse.',
    hours: ['Vendredi · 12:00–22:30', 'Samedi · 12:00–23:00'],
    diets: ['Végétarien', 'Sans gluten'],
    loyalty: {
      type: 'stamps',
      title: 'Le carnet rouge',
      current: 4,
      target: 10,
      reward: 'Un plat du jour offert',
      rule: 'Une coche par visite.',
      style: 'braise',
    },
    menu: [
      { name: 'Curry rouge', description: 'Lait de coco, légumes croquants et basilic thaï.', price: '16,50 €' },
      { name: 'Riz sauté maison', description: 'Œuf, légumes et sauce tamarin.', price: '14,90 €' },
    ],
  },
  {
    id: 'braise',
    name: 'Braise & Basilic',
    shortName: 'Braise & Basilic',
    cuisine: 'Cuisine méditerranéenne',
    district: 'Paris 3e',
    distance: '2,3 km',
    rating: '4,5',
    image: '/images/tacos.webp',
    address: '5 rue de Bretagne, Paris 3e',
    description: 'Cuissons au feu, légumes de saison et grandes assiettes méditerranéennes.',
    hours: ['Vendredi · 12:00–23:00', 'Samedi · 12:00–23:30'],
    diets: ['Halal', 'Végétarien'],
    loyalty: {
      type: 'stamps',
      title: 'Les braises fidèles',
      current: 3,
      target: 8,
      reward: 'Une entrée offerte',
      rule: 'Une coche par passage.',
      style: 'creme',
    },
    menu: [
      { name: 'Aubergine braisée', description: 'Yaourt citronné, herbes et noisettes.', price: '15,00 €' },
      { name: 'Poulet au feu', description: 'Épices douces, pommes grenailles et jus corsé.', price: '19,00 €' },
    ],
  },
]

export const feedPosts = [
  {
    id: 1,
    restaurantId: 'casa',
    author: 'Casa Verde',
    district: 'Paris 11e',
    image: '/images/tacos.webp',
    likes: 285,
    text: 'Les tortillas sont pressées chaque matin. Aujourd’hui : légumes rôtis, salsa verde et citron frais.',
    time: 'Il y a 18 min',
  },
  {
    id: 2,
    restaurantId: 'amina',
    author: 'Camille R.',
    handle: '@camilleatable · Chez Amina',
    image: '/images/table.webp',
    likes: 126,
    text: 'Le couscous du vendredi qui met tout le monde d’accord. J’ai aussi avancé ma carte fidélité.',
    time: 'Il y a 1 h',
  },
  {
    id: 3,
    restaurantId: 'miso',
    author: 'Atelier Miso',
    district: 'Paris 10e',
    image: '/images/ramen.webp',
    likes: 173,
    text: 'Un bouillon végétal précis et généreux, servi ce soir à l’atelier.',
    time: 'Il y a 2 h',
  },
]

export const historyItems = [
  { id: 1, restaurantId: 'miso', title: 'Visite enregistrée', date: '3 juil. 2026 à 21:10', amount: '+220', balance: '500' },
  { id: 2, restaurantId: 'amina', title: 'Points de commande', date: '4 juil. 2026 à 20:41', amount: '+2', balance: '5' },
  { id: 3, restaurantId: 'amina', title: 'Ajustement de fidélité', date: '5 juil. 2026 à 09:00', amount: '+1', balance: '6' },
  { id: 4, restaurantId: 'casa', title: 'Commande enregistrée', date: '6 juil. 2026 à 20:30', amount: '+190', balance: '640' },
  { id: 5, restaurantId: 'miso', title: 'Article remboursé', date: '8 juil. 2026 à 10:06', amount: '-50', balance: '590' },
]

export const getRestaurant = (id) => restaurants.find((restaurant) => restaurant.id === id) || restaurants[0]
